# Generated by Django 3.2.18 on 2023-04-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.SmallIntegerField()),
                ('photo', models.ImageField(upload_to='students_images/')),
            ],
        ),
    ]
